### ISSUE TITLE
What's the difference between this and the starter micro api?

### ISSUE THREAD

**Issue by AstroLive8333** [cyclic-software/starter-express-api#6]
Which one should I use?

(Or which one is used for what? EX: express might be used for websites whereas micro might be used for games or something idk)

**Comment by seekayel** [comment]
Good question. Both are very basic starters. The only difference is one relies on Express and the other uses the built in http module inside of node.

Express usage: https://github.com/cyclic-software/starter-express-api/blob/e575514470a867a65a9e4eff413e1fd728c83d62/index.js#L1

http usage: https://github.com/cyclic-software/starter-micro-api/blob/0e63791e04afa9f0703473d0cdf3ee04c2fbb32c/index.js#L1
