### ISSUE TITLE
set process.env.PORT not work bug?

### ISSUE THREAD

**Issue by xgqfrms** [cyclic-software/starter-express-api#76]
# set process.env.PORT not work bug?

>  So is there no way to change the server port?

![image](https://github.com/cyclic-software/starter-express-api/assets/7291672/5b68a4a2-1b05-4693-aa2b-1eb7ff063902)

https://github.com/web-full-stack/cyclic-express-server#cyclic-bug

```js
const fs = require('node:fs');
const path = require('node:path');
const express = require('express');
const app = express();

app.use(express.static(__dirname + '/public'),
  // 
);
app.use(express.static(__dirname + '/static'),
  // 
);

app.get('/', (req, res) => {
  fs.readFile(__dirname + '/public/index.html', 'utf8', (err, text) => {
    res.send(text);
  });
});


// const defaultPort = 3000;
// const port = process.env.PORT || defaultPort
// console.log(`❓process.env.PORT =`, process.env.PORT) 

const port = 8888;
console.log(`❓port = ${port}`)

app.listen(port, () => {
  console.log(`app is running on http://localhost:${port}`)
});

```

## the `process.env.PORT` variable not work at all

![image](https://github.com/cyclic-software/starter-express-api/assets/7291672/51e1f9c0-a80b-4b73-be22-5a1fe4e3b3be)

**Comment by seekayel** [comment]
I looks like the app started on `8888` correctly. I'm not understanding what the expected behavior was and what the actual behavior was?

**Comment by xgqfrms** [comment]
I mean why I can't visit this URL with the port `8888`.

That's to say, any port will be automatically changed to port `443` when HTTPS is enabled.

https://cyclic-express-server.cyclic.cloud ✅

https://cyclic-express-server.cyclic.cloud:443 ✅

https://cyclic-express-server.cyclic.cloud:8888/ ❌


So it's not possible to change the port by setting process.env.PORT, right?

**Comment by seekayel** [comment]
All cyclic apps are exposed with SSL enabled on 443 to the world. The `process.env.PORT` is just the port the server listens on internally behind the load balancer.
